/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentClassRouteImport } from './routes/assignment/class'
import { Route as AssignmentStudentRouteImport } from './routes/assignment/student'
import { Route as ClassIndexRouteImport } from './routes/class/index'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ExamExamIdRouteImport } from './routes/exam/$examId'
import { Route as ClassClassIdTabRouteImport } from './routes/class/$classId.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentClassRoute = AssignmentClassRouteImport.update({
  id: '/assignment/class',
  path: '/assignment/class',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentStudentRoute = AssignmentStudentRouteImport.update({
  id: '/assignment/student',
  path: '/assignment/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIndexRoute = ClassIndexRouteImport.update({
  id: '/class/',
  path: '/class/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdTabRoute = ClassClassIdTabRouteImport.update({
  id: '/class/$classId/$tab',
  path: '/class/$classId/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignment/class': typeof AssignmentClassRoute
  '/assignment/student': typeof AssignmentStudentRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/class/': typeof ClassIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/class/$classId/$tab': typeof ClassClassIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignment/class': typeof AssignmentClassRoute
  '/assignment/student': typeof AssignmentStudentRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/class': typeof ClassIndexRoute
  '/exam': typeof ExamIndexRoute
  '/class/$classId/$tab': typeof ClassClassIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignment/class': typeof AssignmentClassRoute
  '/assignment/student': typeof AssignmentStudentRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/class/': typeof ClassIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/class/$classId/$tab': typeof ClassClassIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignment/class'
    | '/assignment/student'
    | '/exam/$examId'
    | '/class/'
    | '/exam/'
    | '/class/$classId/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignment/class'
    | '/assignment/student'
    | '/exam/$examId'
    | '/class'
    | '/exam'
    | '/class/$classId/$tab'
  id:
    | '__root__'
    | '/'
    | '/assignment/class'
    | '/assignment/student'
    | '/exam/$examId'
    | '/class/'
    | '/exam/'
    | '/class/$classId/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentClassRoute: typeof AssignmentClassRoute
  AssignmentStudentRoute: typeof AssignmentStudentRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  ClassIndexRoute: typeof ClassIndexRoute
  ExamIndexRoute: typeof ExamIndexRoute
  ClassClassIdTabRoute: typeof ClassClassIdTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment/class': {
      id: '/assignment/class'
      path: '/assignment/class'
      fullPath: '/assignment/class'
      preLoaderRoute: typeof AssignmentClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment/student': {
      id: '/assignment/student'
      path: '/assignment/student'
      fullPath: '/assignment/student'
      preLoaderRoute: typeof AssignmentStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/': {
      id: '/class/'
      path: '/class'
      fullPath: '/class/'
      preLoaderRoute: typeof ClassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/$tab': {
      id: '/class/$classId/$tab'
      path: '/class/$classId/$tab'
      fullPath: '/class/$classId/$tab'
      preLoaderRoute: typeof ClassClassIdTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentClassRoute: AssignmentClassRoute,
  AssignmentStudentRoute: AssignmentStudentRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  ClassIndexRoute: ClassIndexRoute,
  ExamIndexRoute: ExamIndexRoute,
  ClassClassIdTabRoute: ClassClassIdTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
